// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"gorm.io/gorm"
	"time"
	"wilder.cn/gogo/comm"
)

const TableNameAClubdoc = "a_clubdocs"

// AClubdoc mapped from table <a_clubdocs>
type AClubdoc struct {
	ID      int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Clubid  int32     `gorm:"column:clubid" json:"clubid"`            // 团队编号与a_clubs中的id关联
	Docid   int32     `gorm:"column:docid" json:"docid"`              // 文档编号，与a_docs中的id关联
	Addtime time.Time `gorm:"column:addtime;not null" json:"addtime"` // 加入时间
}

// TableName AClubdoc's table name
func (*AClubdoc) TableName() string {
	return TableNameAClubdoc
}
func (ad *AClubdoc) BeforeCreate(tx *gorm.DB) error {
	ad.Addtime=comm.LocalTime()
	return nil
}