// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"gorm.io/gorm"
	"time"
	"wilder.cn/gogo/comm"
)

const TableNameAClub = "a_clubs"

// AClub mapped from table <a_clubs>
type AClub struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name" json:"name"`                      // 团队空间名称
	Createtime time.Time `gorm:"column:createtime;not null" json:"createtime"` // 创建时间
	Describe   string    `gorm:"column:describe" json:"describe"`              // 空间描述
	Ownerid    string    `gorm:"column:ownerid" json:"ownerid"`                // 用户编号，与s_user关联
}

// TableName AClub's table name
func (*AClub) TableName() string {
	return TableNameAClub
}
func (ad *AClub) BeforeCreate(tx *gorm.DB) error {
	ad.Createtime=comm.LocalTime()
	return nil
}