// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"time"
)

const TableNameAShare = "a_shares"

// AShare mapped from table <a_shares>
type AShare struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name" json:"name"`                    // 分享名称
	Code       string    `gorm:"column:code" json:"code"`                    // 分享链接编码用于接入，生成访问链接
	Docid      int32     `gorm:"column:docid;not null" json:"docid"`         // 文档编号
	Validtime  time.Time `gorm:"column:validtime;not null" json:"validtime"` // 有效期，过期不能访问
	Clicktimes int32     `gorm:"column:clicktimes" json:"clicktimes"`        // 点击次数
	State      int32     `gorm:"column:state" json:"state"`                  // 状态：1可以访问，0,禁用
	Type       int32     `gorm:"column:type" json:"type"`                    // 访问类型：1外部公开，不要账号；0,需要使用账号才能访问
}

// TableName AShare's table name
func (*AShare) TableName() string {
	return TableNameAShare
}
