// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"time"
)

const TableNameAUserdoc = "a_userdocs"

// AUserdoc mapped from table <a_userdocs>
type AUserdoc struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 流水号
	Userid      string    `gorm:"column:userid" json:"userid"`                       // 用户编号，与s_user中id关联
	Docid       int32     `gorm:"column:docid;not null" json:"docid"`                // 文档编号表
	Lastread    time.Time `gorm:"column:lastread" json:"lastread"`                   // 文档阅读记录表
	Currentpage int32     `gorm:"column:currentpage" json:"currentpage"`             // 读到第几页
}

// TableName AUserdoc's table name
func (*AUserdoc) TableName() string {
	return TableNameAUserdoc
}
