// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"gorm.io/gorm"
	"time"
	"wilder.cn/gogo/comm"
)

const TableNameSDepartment = "s_departments"

// SDepartment mapped from table <s_departments>
type SDepartment struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 编号
	Name       string    `gorm:"column:name" json:"name"`                           // 组织名称
	Createtime time.Time `gorm:"column:createtime;not null" json:"createtime"`      // 创建时间
}

// TableName SDepartment's table name
func (*SDepartment) TableName() string {
	return TableNameSDepartment
}
func (ad *SDepartment) BeforeCreate(tx *gorm.DB) error {
	ad.Createtime=comm.LocalTime()
	return nil
}