// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameSDepuser = "s_depusers"

// SDepuser mapped from table <s_depusers>
type SDepuser struct {
	Userid       string `gorm:"column:userid;primaryKey" json:"userid"`             // 用户编号
	Departmentid int32  `gorm:"column:departmentid;primaryKey" json:"departmentid"` // 组织编号
}

// TableName SDepuser's table name
func (*SDepuser) TableName() string {
	return TableNameSDepuser
}
