// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameSGroupuser = "s_groupuser"

// SGroupuser mapped from table <s_groupuser>
type SGroupuser struct {
	Groupid int32  `gorm:"column:groupid;primaryKey" json:"groupid"` // 组编号
	Userid  string `gorm:"column:userid;primaryKey" json:"userid"`   // 用户编号
}

// TableName SGroupuser's table name
func (*SGroupuser) TableName() string {
	return TableNameSGroupuser
}
