// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"gorm.io/gorm"
	"time"
	"wilder.cn/gogo/comm"
)

const TableNameSLog = "s_logs"

// SLog mapped from table <s_logs>
type SLog struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Account   string    `gorm:"column:account" json:"account"`
	IP        string    `gorm:"column:ip" json:"ip"`
	Logintime time.Time `gorm:"column:logintime;not null" json:"logintime"`
}

// TableName SLog's table name
func (*SLog) TableName() string {
	return TableNameSLog
}
func (ad *SLog) BeforeCreate(tx *gorm.DB) error {
	ad.Logintime=comm.LocalTime()
	return nil
}