// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameSOperator = "s_operators"

// SOperator mapped from table <s_operators>
type SOperator struct {
	ID   int32  `gorm:"column:id;primaryKey" json:"id"`
	Name string `gorm:"column:name" json:"name"`
}

// TableName SOperator's table name
func (*SOperator) TableName() string {
	return TableNameSOperator
}
