// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameSResource = "s_resources"

// SResource mapped from table <s_resources>
type SResource struct {
	Resid    int32  `gorm:"column:resid;primaryKey;autoIncrement:true" json:"resid"` // 资源编号
	Userid   string `gorm:"column:userid;primaryKey" json:"userid"`                  // 拥有者编号
	Read     bool   `gorm:"column:read" json:"read"`                                 // 用户读权限
	Write    bool   `gorm:"column:write" json:"write"`                               // 用户写权限
	Download bool   `gorm:"column:download" json:"download"`                         // 用户下载权限
}

// TableName SResource's table name
func (*SResource) TableName() string {
	return TableNameSResource
}
