// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameSRoleoperator = "s_roleoperator"

// SRoleoperator mapped from table <s_roleoperator>
type SRoleoperator struct {
	Roleid     int32 `gorm:"column:roleid;primaryKey" json:"roleid"`         // 角色编号
	Operatorid int32 `gorm:"column:operatorid;primaryKey" json:"operatorid"` // 操作功能的编号
	Acte       bool  `gorm:"column:acte" json:"acte"`                        // 是否可以操作
}

// TableName SRoleoperator's table name
func (*SRoleoperator) TableName() string {
	return TableNameSRoleoperator
}
