// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

const TableNameSRolegroup = "s_rolegroup"

// SRolegroup mapped from table <s_rolegroup>
type SRolegroup struct {
	Roleid  int32 `gorm:"column:roleid;primaryKey" json:"roleid"`   // 角色编号
	Groupid int32 `gorm:"column:groupid;primaryKey" json:"groupid"` // 组编号
}

// TableName SRolegroup's table name
func (*SRolegroup) TableName() string {
	return TableNameSRolegroup
}
