// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"gorm.io/gorm"
	"time"
	"wilder.cn/gogo/comm"
)

const TableNameSRole = "s_role"

// SRole mapped from table <s_role>
type SRole struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 角色编号
	Name       string    `gorm:"column:name" json:"name"`                           // 角色名称
	Createtime time.Time `gorm:"column:createtime;not null" json:"createtime"`      // 创建时间
}

// TableName SRole's table name
func (*SRole) TableName() string {
	return TableNameSRole
}
func (ad *SRole) BeforeCreate(tx *gorm.DB) error {
	ad.Createtime=comm.LocalTime()
	return nil
}