// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"time"
)

const TableNameSSearch = "s_search"

// SSearch mapped from table <s_search>
type SSearch struct {
	ID       int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Account  string    `gorm:"column:account" json:"account"`            // 用户账号
	IP       string    `gorm:"column:ip" json:"ip"`                      // 用户的地址
	Opertime time.Time `gorm:"column:opertime;not null" json:"opertime"` // 操作时间
	Detail   string    `gorm:"column:detail" json:"detail"`              // 搜索内容
}

// TableName SSearch's table name
func (*SSearch) TableName() string {
	return TableNameSSearch
}
